version: "3"
services:
    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        container_name: database
        environment:
            - MYSQL_ROOT_PASSWORD=${mysql_root_password}
            - MYSQL_DATABASE=${mysql_database}
        networks:
            - to_sql
        ports:
            - "8306:3306"
        volumes:
            - data:/var/lib/mysql
        restart: always
    app:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile
        container_name: app
        environment:
            - DB_HOST=${mysql_host}
            - DB_USER=${mysql_user}
            - DB_PASSWORD=${mysql_root_password}
            - DB_DATABASE=${mysql_database}
        networks:
            - to_sql
        volumes:
            - ./to_sql:/app/to_sql
            - ./pyproject.toml:/app/pyproject.toml
            - ./poetry.lock:/app/poetry.lock
            - ./tests:/app/tests
        restart: "no"
        depends_on:
            - mysql
volumes:
    data:
networks:
    to_sql: